### PR TITLE
README.md file with project information

### PR DESCRIPTION
**Pull request by Daniel-Ezekiel**
This pull request updated the README.md file with the project description and a contribution guideline for other developers.
Kindly let me know if there's anything that should be added or removed.

34992497-d22cdbeb210cdc5b30f7dbac757726c5

### CODE REVIEW

**Review by Phemozil — COMMENTED** [review]
Nice work bro

**Comment by Xarafina** [comment]
Oh okay. I've seen it 👍

**Comment by Xarafina** [comment]
Nice job!

**Comment by Daniel-Ezekiel** [comment]
Thank you, I will go ahead and merge the pull request then.

**Pull request merged**
